apiVersion: backstage.io/v1alpha1
kind: Catalog
metadata:
  name: my-backstage-catalog
spec:
  relations:
    - type: owner
      target: User:john.doe@example.com
    - type: member
      target: User:jane.doe@example.com
    - type: depends-on
      target: API:my-api-group:my-api:v1
  users:
    - kind: User
      metadata:
        name: john.doe@example.com
      spec:
        displayName: John Doe
    - kind: User
      metadata:
        name: jane.doe@example.com
      spec:
        displayName: Jane Doe
  apis:
    - kind: API
      metadata:
        namespace: my-api-group
        name: my-api
        version: v1
      spec:
        description: |
          This is the description of my API.
        openapi: 3.0.0
        paths:
          /endpoint:
            get:
              summary: Get endpoint
              responses:
                '200':
                  description: OK
