apiVersion: backstage.io/v1alpha1
kind: Catalog
metadata:
  name: my-backstage-catalog
spec:
  relations:
    - type: owns
      target: user:johndoe
    - type: hasPart
      target: user:janedoe
    - type: dependsOn
      target: api:my-api-group:my-api:v1
users:
  - kind: User
    metadata:
      name: johndoe
      email: john.doe@example.com
      displayName: John Doe
  - kind: User
    metadata:
      name: janedoe
      email: jane.doe@example.com
      displayName: Jane Doe
apis:
  - kind: API
    metadata:
      namespace: my-api-group
      name: my-api
      version: v1
    spec:
      type: openapi
      lifecycle: production
      owner: user:johndoe
      definition:
        type: openapi3
        path: openapi.yaml
