apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  description: Sample Service
spec:
  type: service
  owner: team-a
  lifecycle: experimental
  relations:
    - type: uses-service
      target: other-service
      description: This service uses the other-service for data processing.

users:
  - id: admin
    profile:
      displayName: Admin User
      email: admin@example.com
    memberOf: [admins]
  - id: user
    profile:
      displayName: Regular User
      email: user@example.com
    memberOf: [users]

groups:
  - id: admins
    profile:
      displayName: Admins
      description: Group containing admin users.
    members: [admin]
  - id: users
    profile:
      displayName: Users
      description: Group containing regular users.
    members: [user]

apis:
  - id: api-1
    profile:
      displayName: API 1
      description: API for sample service
    access:
      owner: team-a
      lifecycle: production
      type: openapi3
    schema: https://api.example.com/swagger.json
  - id: graphql-api
    profile:
      displayName: GraphQL API
      description: GraphQL API for sample service
    access:
      owner: team-a
      lifecycle: experimental
      type: graphql
    schema: https://api.example.com/graphql
