apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-lookup
  description: Artist Lookup
spec:
  type: service
  owner: team-a
  lifecycle: experimental
  systems:
    - name: Backend System
      description: Manages server-side logic and database interactions.
    - name: Frontend System
      description: Handles user interface and client-side interactions.
    - name: Database System
      description: Stores and manages data persistently.
    - name: Authentication System
      description: Handles user authentication and authorization.
